apiVersion: app/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: silhanr/vprofiledb:latest
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
        ports:
          - name: vprodb-port
            containerPort: 3386
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: app-secret
      nodeSelector:
        zone: us-east-1a
      volumes:
      - name: vpro-db-data
        awsElasticBlockStore:
          volumeID: vol-017c9edc856677db8
          fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args:
            - "rm"
            - "-rf"
            - "/var/lib/mysql/lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
